# Select 10 lowest-energy conformers

In [4]:
import os

input = '/home/ahinostrozac/Documents/programs/Research/unilu/QUED/crest_conformers.xyz'
output = '/home/ahinostrozac/Documents/programs/Research/unilu/QUED/m1301.xyz'
max_conformers = 10

outFile = open(output, 'w')

with open(input, 'r') as inputFile:
    lines = inputFile.readlines()
    line0 = lines[0]
    n = 0 # counter of conformers

    print(line0)
    for line in lines:
        if line.startswith(line0):
            n += 1
            if n>max_conformers:
                break
        outFile.write(line)

  15



In [2]:
import numpy as np
from ase.io import read

def get_atomic_numbers_n_coordinates(inputFile, index):
    ofile = open('tmp.xyz', 'w')
    with open(inputFile, 'r') as ifile:
        lines = ifile.readlines()
        line0 = lines[0]

        # Count total conformers
        total_conformers = sum(1 for line in lines if line.startswith(line0))
        if index >= total_conformers:
            return np.zeros(10), np.zeros(10)

        n = -1
        Z, xyz = [], []
        for line in lines:
            # count one conformer
            if line.startswith(line0):
                n += 1
            # find <index>th conformer
            if n==index:
                ofile.write(line)
                tokens = [x.strip('\n') for x in line.split(' ') if len(x)>0]
                if len(tokens)==4:
                    # extract atomic symbols
                    Z.append(tokens[0])
                    # extract atomic coordinates
                    coor = [float(tokens[1]), float(tokens[2]), float(tokens[3])]
                    xyz.append(coor)
            elif n>index:
                break
            else:
                continue
    return Z, np.array(xyz)

input = '/home/ahinostrozac/Documents/programs/Research/unilu/QUED/crest_conformers.xyz'
get_atomic_numbers_n_coordinates(input, 0)

(['C', 'C', 'C', 'C', 'S', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H'],
 array([[-3.08759953, -0.43627137,  0.0224845 ],
        [-1.89239253,  0.50882936, -0.0079197 ],
        [-0.57125506, -0.25916698, -0.00461352],
        [ 0.61629632,  0.68753418, -0.04368589],
        [ 2.21883035, -0.19460359,  0.0479132 ],
        [-3.0802857 , -1.08950451, -0.84708589],
        [-4.01742242,  0.12689954,  0.02162822],
        [-3.06116487, -1.0554844 ,  0.9161999 ],
        [-1.94404234,  1.13356686, -0.90242732],
        [-1.92788078,  1.16952464,  0.86099492],
        [-0.53618478, -0.92399009, -0.8712101 ],
        [-0.50853896, -0.877616  ,  0.89342811],
        [ 0.62191145,  1.29073549, -0.95143642],
        [ 0.61914184,  1.34982817,  0.82193392],
        [ 2.05407897, -0.90227763, -1.0642628 ]]))

In [ ]:
import numpy as np
from ase.io import read
from ase.atoms import Atoms
import os

def get_atomic_numbers_n_coordinates(inputFile, index):
    ofile = open('tmp.xyz', 'w')
    with open(inputFile, 'r') as ifile:
        lines = ifile.readlines()
        line0 = lines[0]

        # Count total conformers
        total_conformers = sum(1 for line in lines if line.startswith(line0))
        if index >= total_conformers:
            return np.zeros(10), np.zeros(10)

        n = -1
        for line in lines:
            # count one conformer
            if line.startswith(line0):
                n += 1
            # find <index>th conformer
            if n==index:    ofile.write(line)
            elif n>index:   break
            else:           continue
    ofile.close()
    
    # get atomic number and positions of conformer
    atoms = read('tmp.xyz')
    Z = atoms.get_atomic_numbers()
    xyz = atoms.get_positions()
    os.remove('tmp.xyz')
    return Z, xyz

input = '/home/ahinostrozac/Documents/programs/Research/unilu/QUED/crest_conformers.xyz'
Z, xyz = get_atomic_numbers_n_coordinates(input, 17)
mol = Atoms(Z, xyz)

UnknownFileTypeError: Empty file: tmp.xyz

# Get xyz and Z for dftb calculations

In [1]:
import os

import numpy as np
import random
import math

from ase.atoms import Atoms
from ase.calculators.dftb import Dftb
from ase.units import Hartree, Bohr
                

In [ ]:
# get xyz and Z arrays from xyz file
def get_xyz(inputFile, index):
    with open(inputFile, 'r') as ifile:
        lines = ifile.readlines()
        line0 = lines[0]

        n = 0
        Z, xyz = [], []
        for line in lines:
            # count one conformer
            if line.startswith(line0):
                n += 1
            # find <index>th conformer
            if n==index:
                tokens = [x.strip('\n') for x in line.split(' ') if len(x)>0]
                if len(tokens)==4:
                    # extract atomic symbols
                    Z.append(tokens[0])
                    # extract atomic coordinates
                    coor = [float(tokens[1]), float(tokens[2]), float(tokens[3])]
                    xyz.append(coor)
            elif n>index:
                break
            else:
                continue
    return Z, np.array(xyz)

filename = '/home/ahinostrozac/Documents/programs/Research/unilu/QUED/crest_conformers.xyz'
get_xyz(filename, 1)    

0


(['C', 'C', 'C', 'C', 'S', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H'],
 array([[-3.08759953, -0.43627137,  0.0224845 ],
        [-1.89239253,  0.50882936, -0.0079197 ],
        [-0.57125506, -0.25916698, -0.00461352],
        [ 0.61629632,  0.68753418, -0.04368589],
        [ 2.21883035, -0.19460359,  0.0479132 ],
        [-3.0802857 , -1.08950451, -0.84708589],
        [-4.01742242,  0.12689954,  0.02162822],
        [-3.06116487, -1.0554844 ,  0.9161999 ],
        [-1.94404234,  1.13356686, -0.90242732],
        [-1.92788078,  1.16952464,  0.86099492],
        [-0.53618478, -0.92399009, -0.8712101 ],
        [-0.50853896, -0.877616  ,  0.89342811],
        [ 0.62191145,  1.29073549, -0.95143642],
        [ 0.61914184,  1.34982817,  0.82193392],
        [ 2.05407897, -0.90227763, -1.0642628 ]]))

# Read xgboost results

In [2]:
import numpy as np

filename = '/home/ahinostrozac/Documents/programs/Research/unilu/tox2/xgb/minenergy/bob/all/5000/5000pts.npz'
data = np.load(filename, allow_pickle=True)

print("Keys in file:", data.files)
print("Type of hyperparams entry:", type(data['hyperparams'][()]))
print("Raw hyperparams value:", data['hyperparams'])

Keys in file: ['hyperparams', 'X_train_idxs', 'X_test_idxs', 'y_train', 'y_test', 'train_predictions', 'test_predictions']
Type of hyperparams entry: <class 'dict'>
Raw hyperparams value: {'colsample_bytree': 0.5, 'learning_rate': 0.008, 'max_depth': 11, 'min_child_weight': 2, 'n_estimators': 4000, 'reg_alpha': 0.0036850278790095843, 'reg_lambda': 0.015910219986510248, 'subsample': 0.7000000000000001}


In [10]:
data['test_predictions']

array([2.401, 1.974, 1.901, ..., 1.486, 2.236, 2.437], dtype=float32)

In [11]:

filename = '/home/ahinostrozac/Documents/programs/Research/unilu/tox2/krr/minenergy/bob/all/gau/5000/5000pts.npz'
data = np.load(filename, allow_pickle=True)
list(data.keys())

['weights',
 'hyperparams',
 'X_train_idxs',
 'X_val_idxs',
 'X_test_idxs',
 'y_train',
 'y_val',
 'y_test',
 'val_predictions',
 'test_predictions']

In [12]:
data['hyperparams']

array({'alpha': 0.00044691627612702305, 'beta': None, 'ker1_metric': 'minkowski', 'ker1_metric_kwargs': {'p': 2.0}, 'ker1_pow': None, 'ker1_type': 'gau', 'ker2_metric': None, 'ker2_metric_kwargs': None, 'ker2_pow': None, 'ker2_type': None, 'sigma1': 9051.54696666997, 'sigma2': None},
      dtype=object)